Crud adjustments
Groupyz/User pull request #18
Opened 2023-06-05 16:58 UTC by Omer-Leibo

2023-08-03 12:56 UTC, ndvisme requested changes
@Omer-Leibo 
I added a few bullits. 
The main recurring problem, is that the code isn't very dynamic. 
Small change should do the trick.

2023-08-03 12:56 UTC, ndvisme commented on api/tests/test_crud.py
@Omer-Leibo,

1. Regarding this method - 'assert_user_details', i'm prettry sure that if the response or the user dosn't have one of the wanted values, this will throw an exception. It's better practice to change it to a get method. Example: change this --> user['first_name'], to something in the likes of user.get('first_name') .This won't throw an exception, but insted return a none value.
2. 'assert_user_details', is their a more dynamic way to check that the values are equal? (i'm pretty sure there is). If we add more fields to the user model, we'll need to add manually another assert here. 
3.  This string - 'ERROR! user id not found' is found in multiple places in the code. It should become a variable (one place change it all principle) 
4.  I think this will throw an exception if the value is missing -  response.get_json()['message'] (as said in the first bullit) 
5.  Also this string is reaccuring: '/user', please change this to a variable. If you see multiple instances of a string which has the same value, it's usally best to make it a static variable  
6. This also reacurrs a few times in the file: data = {"first_name": "test", "last_name": "user_2", "password": "11", "email": "test_user_3@gmail.com"} (creating a user with json data), make a function which return a json user data. Again if something changes in the user model, insstead of changing it multiple times, we'll need to update the code only in a single place.

2023-08-09 16:04 UTC, StavTasa approved these changes

2023-08-09 16:05 UTC, StavTasa approved these changes

2023-08-15 17:34 UTC, ndvisme requested changes
@Omer-Leibo, I added comments on the files

2023-08-15 17:34 UTC, ndvisme commented on api/routes.py
Looks good.

2023-08-15 17:34 UTC, ndvisme commented on api/tests/test_crud.py
@Omer-Leibo 
1.  On line 7 & 6. Why aren't you using the values from the dbErrors? Think about the "one place change it all"/ "one source of truth"
2. Lines 40, 42 68 & so one... why is there comments here? they seem unneeded.

2023-08-22 13:03 UTC, ndvisme approved these changes
@Omer-Leibo, looks good.
Checking it now.

2023-08-22 13:03 UTC, merged